name: Deploy Allure Report to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies and Allure CLI
      run: |
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y default-jre
        curl -o allure.tgz -L https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
        tar -zxvf allure.tgz
        sudo mv allure-2.27.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure

    - name: Download history from gh-pages
      run: |
        git clone --depth=1 --branch gh-pages https://github.com/${{ github.repository }} gh-pages-temp
        mkdir -p allure-results/history
        cp -R gh-pages-temp/history/* allure-results/history/ || echo "No previous history found"

    - name: Debug previous history before test
      run: ls -R allure-results/history || echo "No files found in previous history"

    - name: Run tests and generate Allure report
      run: |
        pytest --alluredir=allure-results || true
        allure generate allure-results -o allure-report --clean

    - name: Debug new history after generation
      run: ls -R allure-report/history || echo "No history generated"

    - name: Upload Allure report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report

    - name: Deploy to GitHub Pages with history
      run: cp -R allure-report/history ./history
      continue-on-error: true

    - name: Push to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
        keep_files: true
